### PR TITLE
Fix autoimport

### PR DESCRIPTION
**Pull request by delvh**

### CODE REVIEW

**Comment by LeviUniAcc** [comment]
why did you remove the comment?
can we remove the scan from the repos then or not?

**Comment by delvh** [comment]
Because it won't be needed after this PR.
That's exactly why I named it `fix autoimport`, and why I proposed the changes recently.
When this file is at the right location, Spring will automatically query the components in this package.

**Comment by madebyTimo** [comment]
yes, it was my mistake, I placed the meta data wrong

**Comment by LeviUniAcc** [comment]
ok so we can remove the annotation extension again?

**Review by madebyTimo — APPROVED** [review]

**Comment by delvh** [comment]
@LeviUniAcc yes, you can.

**Comment by madebyTimo** [comment]
We should also step up the version. Maybe to `1.0.0` if this now really works?

**Comment by delvh** [comment]
Ah, perhaps we should add a test first before we do that…

**Comment by madebyTimo** [comment]
We can also add unit tests afterwards. They change nothing on the released code

**Comment by delvh** [comment]
Fair enough.
@LeviUniAcc, could you please approve?
Then we'll release `1.0.0`.

**Review by LeviUniAcc — APPROVED** [review]

**Comment by LeviUniAcc** [comment]
done sry

**Pull request merged**
